services:
    dnsdock:
        image: p1c2u/dnsdock
        container_name: dnsdock
        command: -nameserver 192.168.0.1:53 -nameserver 8.8.8.8:53
        volumes:
            - /var/run/docker.sock:/run/docker.sock
        ports:
            - 172.17.0.0:53:53/udp
