name: Release workflow

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@v0.8.0
        with:
          devbox-version: 0.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish release
        run: devbox run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
